### ISSUE TITLE
Allow specifying own hostname

### ISSUE THREAD

**Issue by geoah** [nimona/go-nimona#154]
Allow for either a `--announce-address` arg or a `NIMONA_ANNOUNCE_ADDRESS` env var to force the local address to be set to its value. This should allow bootstrap nodes to always announce their addresses as their hostnames.

**Comment by geoah** [comment]
@kootoopas ❤️ will add some more details on this to walk you through the parts you might need to touch :D

**Comment by 2007heaven** [comment]
@geoah NO. I want to figure this out. :P

**Comment by 2007heaven** [comment]
@geoah I can figure your architecture in 10 minutes if I want to...

**Comment by geoah** [comment]
Architecture is a very strong word for the networking part of this :p Feel free to move things around or to open tickets for things that make no sense.
