### ISSUE TITLE
Remote-hosted nimona.io url imports return 404

### ISSUE THREAD

**Issue by 2007heaven** [nimona/go-nimona#155]
Do you guys alias `nimona.io/go/` to the local `go-nimona` package path in your editors? GoLand can't resolve them.

**ENV**
* os: macOS 10.13.6 (high sierra)
* go: go1.10.3 darwin/amd64
* editor: GoLand 2018.3 EAP

**STR**
Visit any remote-hosted `go-nimona` dependency: https://nimona.io/go/primitives

**ER**
View some sort of info designating it's a git repo.

**AR**
Get 404.

**Comment by geoah** [comment]
@kootoopas yeah we kinda suck at docs.

Canonical package name is `nimona.io/go`.
You should be able to either `go get nimona.io/go` or even better `git clone git@github.com:nimona/go-nimona.git $GOPATH/src/nimona.io/go`.

After that doing a `dep ensure` in `$GOPATH/src/nimona.io/go` should be all you need to be able to run the main cli with `go run nimona.io/go/cmd/nimona`.

I'm updating the readme now, thanks for opening this. :)

**Comment by 2007heaven** [comment]
@geoah Np. I tried manually go getting but obviously 404 persists.

**Comment by geoah** [comment]
@kootoopas hm, weird, did you try to manually get the dependency of the root package?
