### ISSUE TITLE
Unify configuration options

### ISSUE THREAD

**Issue by geoah** [nimona/go-nimona#162]
As @kootoopas correctly pointed out, config options are a bit of a mess.

It would be nice to have a common config for all the global configuration values.
There are three different ways to configure different parts of the daemon or cli.

* config file (`.nimona/config`
  * [ ] peer key (`.key`)
* env vars
  * [ ] log level (`LOG_LEVEL`)
  * [ ] show debug info for blocks (`DEBUG_BLOCKS`)
  * [ ] upnp support (`UPNP`)
  * [ ] telemetry client support (`TELEMETRY`)
  * [ ] announce local addresses (`BIND_LOCAL` which might just be the worst env name ever)
  * [ ] announce ipv6 addresses (`BIND_IPV6` same as above)
  * [ ] telemetry server config (`TELEMETRY_*`)
* command line args
  * [ ] announce hostname (`--announce-hostname`)
  * [ ] api address (`--api`)
  * [ ] config path (`--config`)
  * [ ] env (`--env` I'm not even sure what this does)

**Comment by 2007heaven** [comment]
We should probably establish an order of precedence for options, in case one appears on cli, config file and in the environment for a single execution. I propose in order of descending priority:
1. cli arg
2. config file key
3. env var

Thoughts?

**Comment by geoah** [comment]
Assuming we'll go with [viper](https://github.com/spf13/viper) (since we are already using [cobra](https://github.com/spf13/cobra)) we would just stick to their precedence as they [don't seem to support changing the order](https://github.com/spf13/viper/issues/388).

> Viper uses the following precedence order. Each item takes precedence over the item below it:
> 
> * explicit call to Set
> * flag
> * env
> * config
> * key/value store
> * default

**Comment by 2007heaven** [comment]
It's a bit weird that env precedes the config file but other than that got no issue.

**Comment by geoah** [comment]
daemon has been refactored, flags are no longer a thing
