### ISSUE TITLE
Sql Store v2

### ISSUE THREAD

**Issue by superdecimal** [nimona/go-nimona#276]
- [ ] split into two tables, one for objects, one for relationships, as currently the split interface doesn't match what it does

- [ ] consider renaming package to sql or something as rel is confusing
- [ ] StreamStore interface is not implemented
- [ ] replace subscriptions with individual queues
- [ ] consider replacing TTL column with expiration date to optimise gc()

**Comment by geoah** [comment]
reopening until I actually add those as individual tickets :D
